apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-user-transactions
  labels:
    app: streaming-cep
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: bank-user-transactions
  partitions: "3"
  replicas: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-rewards
  labels:
    app: streaming-cep
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: bank-rewards
  partitions: "1"
  replicas: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-ops-credit-management
  labels:
    app: streaming-cep
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: bank-ops-credit-management
  partitions: "1"
  replicas: "1"
